version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install && npm install serve
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - serve -s build